language: r

sudo: required

env:
   global:
     - r_build_args="--no-build-vignettes --no-manual"
     - r_check_args="--no-build-vignettes --no-manual --as-cran"
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
